export default people = [
  {
    key: 1,
    name: '佐々木',
    price: 2400,
    nDrinks: 5,
    drinkType: 'Hard',
    check: false,
    readyEdit: false,
  },
  {
    key: 2,
    name: '佐々木',
    price: 2400,
    nDrinks: 5,
    drinkType: 'Hard',
    check: false,
    readyEdit: true,
  },
  {
    key: 3,
    name: '佐々木',
    price: 2400,
    nDrinks: 5,
    drinkType: 'Hard',
    check: false,
    readyEdit: false,
  },
  {
    key: 4,
    name: '佐々木',
    price: 2400,
    nDrinks: 5,
    drinkType: 'Hard',
    check: false,
    readyEdit: false,
  },
  {
    key: 5,
    name: '佐々木',
    price: 2400,
    nDrinks: 5,
    drinkType: 'Hard',
    check: false,
    readyEdit: false,
  },
];
